apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yaml
  - release.yaml
configMapGenerator:
  - name: test-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml