apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: test
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: test
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: test-values